'use strict';
const assert=require('node:assert/strict');const{Matchmaker,MODE_SEATS}=require('../server/matchmaker');
let sequence=0;const create=()=>new Matchmaker({id:()=>`id-${++sequence}`});const player=id=>({id,username:id,messages:[],send(type,payload){this.messages.push({type,payload})}});function test(name,fn){try{fn();process.stdout.write(`✓ ${name}\n`)}catch(error){process.stderr.write(`✗ ${name}\n${error.stack}\n`);process.exitCode=1}}
test('Modların doğru oyuncu kapasitesi vardır',()=>{assert.deepEqual(Object.fromEntries(Object.entries(MODE_SEATS).map(([m,s])=>[m,s.length])),{spvp:2,upvp:4,pistiSolo:2,pistiTeam:4,okeyClassic:4,okeySolo:4,okeyTeam:4,batakKozMaca:4,batakGommeli:4,sozcukDuel:4})});
test('Normal Okey kendi dört kişilik kuyruğunda eşleşir',()=>{const m=create(),players=['n1','n2','n3','n4'].map(player);players.forEach(p=>m.join(p,'okeyClassic'));const match=players[0].messages.find(x=>x.type==='match:found').payload;assert.equal(match.mode,'okeyClassic');assert.deepEqual(match.players.map(p=>p.seat),['P1','P2','P3','P4'])});
test('Sözcük Kapışması dört bağımsız koltukla eşleşir',()=>{const m=create(),players=['1','2','3','4'].map(player);players.forEach(p=>m.join(p,'sozcukDuel'));const match=players[0].messages.find(x=>x.type==='match:found').payload;assert.deepEqual(match.players.map(p=>p.seat),['P1','P2','P3','P4']);assert.ok(match.players.every(p=>p.team===null))});
test('İki kişilik kuyruk eşleşme ve benzersiz koltuk üretir',()=>{const m=create(),a=player('a'),b=player('b');m.join(a,'spvp');const matches=m.join(b,'spvp');assert.equal(matches.length,1);assert.deepEqual(matches[0].players.map(p=>p.seat),['white','black']);assert.equal(a.messages.at(-1).type,'match:found');assert.equal(a.messages.at(-1).payload.matchId,b.messages.at(-1).payload.matchId);assert.equal(m.stats().spvp,0)});
test('Eşli kuyruk A-B-A-B takım koltukları atar',()=>{const m=create(),players=['1','2','3','4'].map(player);players.forEach(p=>m.join(p,'pistiTeam'));const found=players.map(p=>p.messages.find(x=>x.type==='match:found').payload.assignment);assert.deepEqual(found.map(x=>x.seat),['A1','B1','A2','B2']);assert.deepEqual(found.map(x=>x.team),['teamA','teamB','teamA','teamB'])});
test('Aynı oyuncu ikinci kuyruğa geçtiğinde eski bileti temizlenir',()=>{const m=create(),a=player('a');m.join(a,'spvp');m.join(a,'okeySolo');assert.equal(m.stats().spvp,0);assert.equal(m.stats().okeySolo,1)});
test('Ayrılan oyuncu kuyruktan ve indeksten silinir',()=>{const m=create(),a=player('a');m.join(a,'upvp');assert.equal(m.leave('a'),true);assert.equal(m.leave('a'),false);assert.equal(m.stats().upvp,0)});
test('Rakip bulunamazsa 3–4 saniye sonra botlar birer saniye arayla gelir',()=>{let sequence=0;const jobs=[],setTimer=(fn,delay)=>{const job={fn,delay,cancelled:false,unref(){}};jobs.push(job);return job},clearTimer=job=>{job.cancelled=true},m=new Matchmaker({id:()=>`fill-${++sequence}`,setTimer,clearTimer,initialBotDelay:()=>3500,botInterval:1000,createBot:difficulty=>({id:`BOT-${sequence}-${difficulty}`,username:`Misafir A0B00${sequence}`,isBot:true,botDifficulty:difficulty,level:10}),onMatches:matches=>m.completed=matches}),human=player('human');m.join(human,'pistiTeam');assert.equal(jobs.at(-1).delay,3500);jobs.at(-1).fn();assert.equal(human.messages.at(-1).payload.waiting,2);assert.equal(jobs.at(-1).delay,1000);jobs.at(-1).fn();assert.equal(human.messages.at(-1).payload.waiting,3);jobs.at(-1).fn();assert.equal(m.completed.length,1);assert.equal(m.completed[0].players.filter(item=>item.isBot).length,3);assert.ok(m.completed[0].players.slice(1).every(item=>/^Misafir [A-F0-9]{6}$/.test(item.username)));assert.ok(m.completed[0].players.slice(1).every(item=>['ORTA','İYİ'].includes(item.botDifficulty)))});

test('Batak modları dört bireysel P koltuğu üretir',()=>{for(const mode of ['batakKozMaca','batakGommeli']){const m=create(),players=['b1','b2','b3','b4'].map(player);players.forEach(p=>m.join(p,mode));const match=players[0].messages.find(x=>x.type==='match:found').payload;assert.deepEqual(match.players.map(p=>p.seat),['P1','P2','P3','P4']);assert.ok(match.players.every(p=>p.team===null))}});
