(function(global){
  'use strict';
  const MODE_KOZ_MACA='kozMaca',MODE_GOMMELI='gommeli';
  const SUITS=Object.freeze(['clubs','diamonds','hearts','spades']);
  const RANKS=Object.freeze(['2','3','4','5','6','7','8','9','10','J','Q','K','A']);
  const RANK_VALUE=Object.freeze(Object.fromEntries(RANKS.map((rank,index)=>[rank,index+2])));
  const clone=value=>typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));
  function createDeck(){return SUITS.flatMap(suit=>RANKS.map(rank=>({id:`${rank}_${suit}`,rank,suit})))}
  function randomInt(max){if(global.crypto?.getRandomValues){const data=new Uint32Array(1);global.crypto.getRandomValues(data);return data[0]%max}return Math.floor(Math.random()*max)}
  function shuffle(cards){const deck=[...cards];for(let i=deck.length-1;i>0;i--){const j=randomInt(i+1);[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
  function normalizeMode(mode){if(mode==='gommedi')return MODE_GOMMELI;if(mode!==MODE_KOZ_MACA&&mode!==MODE_GOMMELI)throw new Error(`Geçersiz Batak modu: ${mode}`);return mode}
  function normalizePlayers(players){if(!Array.isArray(players)||players.length!==4)throw new Error('Batak tam olarak 4 oyuncu ister.');const ids=new Set();return players.map(player=>{const id=String(player?.id||'');if(!id||ids.has(id))throw new Error('Batak oyuncu kimlikleri benzersiz olmalı.');ids.add(id);return{id,username:player.username||id,avatarUrl:player.avatarUrl||player.avatar||null,level:Number(player.level)||1,seat:player.seat||id,connected:player.connected!==false}})}
  function validateDeck(deck){if(!Array.isArray(deck)||deck.length!==52)throw new Error('Batak destesi 52 kart olmalı.');const ids=new Set();for(const card of deck){if(!card||!SUITS.includes(card.suit)||!RANKS.includes(String(card.rank))||ids.has(card.id))throw new Error('Batak destesinde geçersiz veya yinelenen kart var.');ids.add(card.id)}}
  const HAND_SUIT_ORDER=Object.freeze(['spades','hearts','diamonds','clubs']);
  function sortHand(hand){return hand.sort((a,b)=>HAND_SUIT_ORDER.indexOf(a.suit)-HAND_SUIT_ORDER.indexOf(b.suit)||RANK_VALUE[b.rank]-RANK_VALUE[a.rank])}
  class BatakGame{
    constructor(options={}){this.mode=normalizeMode(options.mode||MODE_KOZ_MACA);this.players=normalizePlayers(options.players||['P1','P2','P3','P4'].map(id=>({id,username:`Oyuncu ${id}`})));this.startingPlayerIndex=Number.isInteger(options.startingPlayerIndex)?((options.startingPlayerIndex%4)+4)%4:0;this.reset(options.deck||null)}
    reset(preShuffledDeck=null){const deck=preShuffledDeck?clone(preShuffledDeck):shuffle(createDeck());validateDeck(deck);const ids=this.players.map(player=>player.id),record=value=>Object.fromEntries(ids.map(id=>[id,clone(value)]));this.state={version:1,mode:this.mode,status:'playing',phase:this.mode===MODE_KOZ_MACA?'bidding':'auction',deck,hands:record([]),kitty:[],buried:[],trump:this.mode===MODE_KOZ_MACA?'spades':null,trumpBroken:false,currentPlayerIndex:this.startingPlayerIndex,leadSuit:null,currentTrick:[],trickNumber:0,bids:record(null),passed:record(false),bidder:null,bidAmount:null,tricksWon:record(0),scores:record(0),winnerPlayerId:null,winners:[],turnDeadlineAt:null};const handSize=this.mode===MODE_GOMMELI?12:13;for(let round=0;round<handSize;round++)for(const player of this.players)this.state.hands[player.id].push(this.state.deck.pop());for(const id of ids)sortHand(this.state.hands[id]);if(this.mode===MODE_GOMMELI)this.state.kitty=this.state.deck.splice(0);return this.getPublicState()}
    player(playerId){const player=this.players.find(item=>item.id===playerId);if(!player)throw new Error('Oyuncu bulunamadı.');return player}
    getCurrentPlayer(){return clone(this.players[this.state.currentPlayerIndex])}
    getHand(playerId){this.player(playerId);return clone(this.state.hands[playerId])}
    getHandCounts(){return Object.fromEntries(this.players.map(player=>[player.id,this.state.hands[player.id].length]))}
    assertTurn(playerId,phase){if(this.state.status!=='playing')throw new Error('Oyun tamamlandı.');if(phase&&this.state.phase!==phase)throw new Error('Bu işlem şu anda yapılamaz.');if(this.getCurrentPlayer().id!==playerId)throw new Error(`Sıra ${this.getCurrentPlayer().username} oyuncusunda.`)}
    advance(){this.state.currentPlayerIndex=(this.state.currentPlayerIndex+1)%4}
    bid(playerId,amount){amount=Number(amount);if(!Number.isInteger(amount))throw new Error('Teklif tam sayı olmalı.');if(this.mode===MODE_KOZ_MACA){this.assertTurn(playerId,'bidding');if(amount<0||amount>13)throw new Error('Koz Maça tahmini 0–13 arasında olmalı.');if(this.state.bids[playerId]!==null)throw new Error('Tahminini zaten söyledin.');this.state.bids[playerId]=amount;if(this.players.every(player=>this.state.bids[player.id]!==null)){this.state.phase='playing';this.state.currentPlayerIndex=this.startingPlayerIndex}else this.advance();return{playerId,amount}}this.assertTurn(playerId,'auction');const minimum=Math.max(5,(this.state.bidAmount||4)+1);if(amount<minimum||amount>13)throw new Error(`İhale en az ${minimum} olmalı.`);this.state.bids[playerId]=amount;this.state.bidder=playerId;this.state.bidAmount=amount;if(amount===13)return this.finishAuction();this.advanceAuction();return{playerId,amount}}
    pass(playerId){if(this.mode!==MODE_GOMMELI)throw new Error('Koz Maça’da herkes tahmin söylemelidir.');this.assertTurn(playerId,'auction');this.state.passed[playerId]=true;this.advanceAuction();return{playerId,pass:true}}
    advanceAuction(){if(!this.state.bidder&&this.players.every(player=>this.state.passed[player.id])){const forced=this.players[this.startingPlayerIndex];this.state.bidder=forced.id;this.state.bidAmount=4;this.state.bids[forced.id]=4;return this.finishAuction()}const eligible=this.players.filter(player=>!this.state.passed[player.id]&&player.id!==this.state.bidder);if(this.state.bidder&&!eligible.length)return this.finishAuction();for(let step=1;step<=4;step++){const index=(this.state.currentPlayerIndex+step)%4,player=this.players[index];if(!this.state.passed[player.id]&&player.id!==this.state.bidder){this.state.currentPlayerIndex=index;return}}this.finishAuction()}
    finishAuction(){const bidder=this.state.bidder;if(!bidder)throw new Error('İhale henüz sonuçlanmadı.');this.state.hands[bidder].push(...this.state.kitty);sortHand(this.state.hands[bidder]);this.state.kitty=[];this.state.phase='bury';this.state.currentPlayerIndex=this.players.findIndex(player=>player.id===bidder);return{bidder,bidAmount:this.state.bidAmount}}
    buryCards(playerId,cardIds){this.assertTurn(playerId,'bury');if(playerId!==this.state.bidder)throw new Error('Kartları yalnız ihaleci gömebilir.');if(!Array.isArray(cardIds)||new Set(cardIds).size!==4)throw new Error('Tam olarak 4 farklı kart gömmelisin.');const hand=this.state.hands[playerId],cards=cardIds.map(id=>hand.find(card=>card.id===id));if(cards.some(card=>!card))throw new Error('Gömmek istediğin kart elinde yok.');this.state.hands[playerId]=hand.filter(card=>!cardIds.includes(card.id));this.state.buried=cards;this.state.phase='trump';return{count:4}}
    selectTrump(playerId,suit){if(this.mode!==MODE_GOMMELI)throw new Error('Koz Maça’da koz her zaman maçadır.');this.assertTurn(playerId,'trump');if(playerId!==this.state.bidder||!SUITS.includes(suit))throw new Error('Geçersiz koz seçimi.');this.state.trump=suit;this.state.phase='playing';return{playerId,suit}}
    highestCard(cards,suit){return cards.filter(play=>play.card.suit===suit).sort((a,b)=>RANK_VALUE[b.card.rank]-RANK_VALUE[a.card.rank])[0]||null}
    winningPlay(){const trick=this.state.currentTrick;if(!trick.length)return null;return this.highestCard(trick,this.state.trump)||this.highestCard(trick,this.state.leadSuit)}
    legalCards(playerId){const hand=this.state.hands[playerId];if(this.state.phase!=='playing'||this.getCurrentPlayer().id!==playerId)return[];if(!this.state.currentTrick.length){const nonTrump=hand.filter(card=>card.suit!==this.state.trump);return this.state.trumpBroken||!nonTrump.length?hand:nonTrump}const lead=this.state.leadSuit,follow=hand.filter(card=>card.suit===lead),trumpInTrick=this.state.currentTrick.some(play=>play.card.suit===this.state.trump);if(follow.length){if(trumpInTrick)return follow;const best=this.highestCard(this.state.currentTrick,lead),higher=follow.filter(card=>RANK_VALUE[card.rank]>RANK_VALUE[best.card.rank]);return higher.length?higher:follow}const trumps=hand.filter(card=>card.suit===this.state.trump);if(!trumps.length)return hand;const playedTrumps=this.state.currentTrick.filter(play=>play.card.suit===this.state.trump),bestTrump=this.highestCard(playedTrumps,this.state.trump),higher=bestTrump?trumps.filter(card=>RANK_VALUE[card.rank]>RANK_VALUE[bestTrump.card.rank]):trumps;return higher.length?higher:trumps}
    isValidMove(playerId,card){return this.legalCards(playerId).some(item=>item.id===card.id)}
    canPlay(playerId,cardId){return this.legalCards(playerId).some(card=>card.id===cardId)}
    playCard(playerId,cardId){this.assertTurn(playerId,'playing');const hand=this.state.hands[playerId],index=hand.findIndex(card=>card.id===cardId);if(index<0)throw new Error('Bu kart elinde yok.');const card=hand[index];if(!this.isValidMove(playerId,card))throw new Error('Renge uyma, yükseltme veya kozlama kuralına aykırı hamle.');hand.splice(index,1);if(!this.state.currentTrick.length)this.state.leadSuit=card.suit;if(card.suit===this.state.trump)this.state.trumpBroken=true;this.state.currentTrick.push({playerId,card:clone(card)});const result={playerId,card:clone(card)};if(this.state.currentTrick.length===4)this.completeTrick();else this.advance();return result}
    completeTrick(){const winner=this.winningPlay(),winnerId=winner.playerId;this.state.tricksWon[winnerId]++;this.state.currentTrick=[];this.state.leadSuit=null;this.state.trickNumber++;this.state.currentPlayerIndex=this.players.findIndex(player=>player.id===winnerId);if(this.state.trickNumber===13)this.finishGame()}
    finishGame(){if(this.mode===MODE_KOZ_MACA){for(const player of this.players){const bid=this.state.bids[player.id],won=this.state.tricksWon[player.id];this.state.scores[player.id]=bid===0?(won===0?10:-10):(won>=bid&&won<=bid+2?won:-bid)}}else for(const player of this.players){const won=this.state.tricksWon[player.id];this.state.scores[player.id]=player.id===this.state.bidder?(won>=this.state.bidAmount?won:-this.state.bidAmount):(won>0?won:-this.state.bidAmount)}const high=Math.max(...Object.values(this.state.scores));this.state.winners=this.players.filter(player=>this.state.scores[player.id]===high).map(player=>player.id);this.state.winnerPlayerId=this.state.winners.length===1?this.state.winners[0]:null;this.state.status='finished';this.state.phase='finished';return{winnerPlayerId:this.state.winnerPlayerId,winners:clone(this.state.winners),scores:clone(this.state.scores)}}
    getPublicState(){return{version:this.state.version,mode:this.mode,status:this.state.status,phase:this.state.phase,players:clone(this.players),trump:this.state.trump,trumpBroken:this.state.trumpBroken,currentPlayer:this.getCurrentPlayer(),currentPlayerIndex:this.state.currentPlayerIndex,leadSuit:this.state.leadSuit,currentTrick:clone(this.state.currentTrick),trickNumber:this.state.trickNumber,bids:clone(this.state.bids),passed:clone(this.state.passed),bidder:this.state.bidder,bidAmount:this.state.bidAmount,tricksWon:clone(this.state.tricksWon),scores:clone(this.state.scores),handCounts:this.getHandCounts(),kittyCount:this.state.kitty.length||(this.state.phase==='bury'?4:0),buriedCount:this.state.buried.length,winnerPlayerId:this.state.winnerPlayerId,winners:clone(this.state.winners),turnDeadlineAt:this.state.turnDeadlineAt}}
    getStateForPlayer(playerId){return{...this.getPublicState(),hand:this.getHand(playerId),yourHand:this.getHand(playerId),legalCardIds:this.legalCards(playerId).map(card=>card.id),canAct:this.getCurrentPlayer().id===playerId}}
    getFullState(){return{...clone(this.state),players:clone(this.players)}}
    setPlayerConnected(playerId,connected){this.player(playerId).connected=Boolean(connected)}
  }
  const api=Object.freeze({BatakGame,MODE_KOZ_MACA,MODE_GOMMELI,SUITS,RANKS,createDeck});global.BATAK=api;if(typeof module!=='undefined'&&module.exports)module.exports=api
})(typeof window!=='undefined'?window:globalThis);
