(function(global){
  'use strict';
  const LETTERS={A:[12,1],B:[2,3],C:[2,4],'Ç':[2,4],D:[2,3],E:[8,1],F:[1,7],G:[1,5],'Ğ':[1,8],H:[1,5],I:[4,2],'İ':[7,1],J:[1,10],K:[7,1],L:[7,1],M:[4,2],N:[5,1],O:[3,2],'Ö':[1,7],P:[1,5],R:[6,1],S:[3,2],'Ş':[2,4],T:[5,1],U:[3,2],'Ü':[2,3],V:[1,7],Y:[2,3],Z:[2,4]};
  const SIZE=15,CENTER=7;
  const EXTRA_WORDS=['TİREN'];
  const clone=v=>JSON.parse(JSON.stringify(v));
  const shuffle=a=>{for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const bonuses=()=>{const out={};const put=(kind,cells)=>cells.forEach(([r,c])=>out[`${r},${c}`]=kind);put('W3',[[0,0],[0,14],[14,0],[14,14],[0,7],[7,0],[7,14],[14,7]]);put('W2',[[1,1],[2,2],[3,3],[4,4],[10,10],[11,11],[12,12],[13,13],[1,13],[2,12],[3,11],[4,10],[10,4],[11,3],[12,2],[13,1],[7,7]]);put('L3',[[1,5],[1,9],[5,1],[5,5],[5,9],[5,13],[9,1],[9,5],[9,9],[9,13],[13,5],[13,9]]);put('L2',[[0,3],[0,11],[2,6],[2,8],[3,0],[3,7],[3,14],[6,2],[6,6],[6,8],[6,12],[7,3],[7,11],[8,2],[8,6],[8,8],[8,12],[11,0],[11,7],[11,14],[12,6],[12,8],[14,3],[14,11]]);return out};
  class WordClashGame{
    constructor(options={}){this.players=(options.players||[{id:'P1',username:'Oyuncu 1'},{id:'P2',username:'Kantin Bot'}]).map(p=>({...p}));this.dictionary=new Set([...(options.dictionary||global.KANTIN_TURKISH_WORDS||[]),...EXTRA_WORDS]);this.bonuses=bonuses();this.start()}
    makeBag(){let n=0,bag=[];for(const [letter,[count,value]] of Object.entries(LETTERS))for(let i=0;i<count;i++)bag.push({id:`h${++n}`,letter,value,blank:false});for(let i=0;i<2;i++)bag.push({id:`h${++n}`,letter:'?',value:0,blank:true});return shuffle(bag)}
    start(){const bag=this.makeBag(),racks=Object.fromEntries(this.players.map(p=>[p.id,bag.splice(0,7)]));this.state={status:'playing',board:Array.from({length:SIZE},()=>Array(SIZE).fill(null)),bag,racks,scores:Object.fromEntries(this.players.map(p=>[p.id,0])),turnIndex:0,turnNumber:1,passes:0,pending:[],history:[],winner:null};return this.getFullState()}
    current(){return this.players[this.state.turnIndex]}
    assertTurn(id){if(this.state.status!=='playing')throw new Error('Oyun tamamlandı.');if(this.current().id!==id)throw new Error('Sıra sende değil.')}
    stage(id,tileId,row,col,blankLetter=null){this.assertTurn(id);row=Number(row);col=Number(col);if(!Number.isInteger(row)||!Number.isInteger(col)||row<0||row>=SIZE||col<0||col>=SIZE)throw new Error('Geçersiz tahta alanı.');if(this.state.board[row][col])throw new Error('Bu alan dolu.');const rack=this.state.racks[id],tile=rack.find(t=>t.id===tileId);if(!tile)throw new Error('Taş ıstakanda değil.');this.state.pending=this.state.pending.filter(x=>x.id!==tileId&&!(x.row===row&&x.col===col));let played={...tile,row,col};if(tile.blank){const letter=String(blankLetter||'').toLocaleUpperCase('tr-TR');if(!LETTERS[letter])throw new Error('Joker için Türkçe bir harf seçmelisin.');played={...played,letter,assignedLetter:letter}}this.state.pending.push(played);return this.getStateForPlayer(id)}
    unstage(id,row,col){this.assertTurn(id);const before=this.state.pending.length;this.state.pending=this.state.pending.filter(x=>x.row!==Number(row)||x.col!==Number(col));if(before===this.state.pending.length)throw new Error('Bu karede geri alınacak harf yok.');return this.getStateForPlayer(id)}
    recall(id){this.assertTurn(id);this.state.pending=[];return this.getStateForPlayer(id)}
    tileAt(row,col){return this.state.pending.find(x=>x.row===row&&x.col===col)||this.state.board[row]?.[col]}
    wordAt(row,col,dr,dc){let r=row,c=col;while(this.tileAt(r-dr,c-dc)){r-=dr;c-=dc}const cells=[];while(this.tileAt(r,c)){cells.push({row:r,col:c,tile:this.tileAt(r,c)});r+=dr;c+=dc}return cells}
    validate(){const p=this.state.pending;if(!p.length)throw new Error('Önce harf yerleştir.');const sameRow=p.every(x=>x.row===p[0].row),sameCol=p.every(x=>x.col===p[0].col);if(!sameRow&&!sameCol)throw new Error('Harfler aynı satırda veya sütunda olmalı.');const dr=sameCol?1:0,dc=sameRow?1:0,word=this.wordAt(p[0].row,p[0].col,dr,dc);if(word.length<2)throw new Error('En az iki harfli bir sözcük kurmalısın.');for(let i=1;i<word.length;i++)if(word[i].row-word[i-1].row!==dr||word[i].col-word[i-1].col!==dc)throw new Error('Sözcüğün içinde boşluk bırakılamaz.');const occupied=this.state.board.some(row=>row.some(Boolean));if(!occupied&&!p.some(x=>x.row===CENTER&&x.col===CENTER))throw new Error('İlk sözcük yıldızlı merkezden geçmeli.');if(occupied&&!p.some(x=>[[1,0],[-1,0],[0,1],[0,-1]].some(([a,b])=>this.state.board[x.row+a]?.[x.col+b])))throw new Error('Yeni sözcük masadaki harflere bağlanmalı.');const candidates=[word];for(const x of p){const cross=this.wordAt(x.row,x.col,dc,dr);if(cross.length>1)candidates.push(cross)}const seen=new Set(),words=candidates.filter(w=>{const key=w.map(x=>`${x.row},${x.col}`).join('|');if(seen.has(key))return false;seen.add(key);return true}),names=words.map(w=>w.map(x=>x.tile.letter).join('').toLocaleUpperCase('tr-TR')),invalid=names.filter(name=>!this.dictionary.has(name));if(invalid.length)throw new Error(`Sözlükte bulunmayan sözcük: ${invalid.join(', ')}`);return words}
    scoreWord(cells){let sum=0,mult=1;for(const x of cells){let value=x.tile.value;if(this.state.pending.some(p=>p.row===x.row&&p.col===x.col)){const b=this.bonuses[`${x.row},${x.col}`];if(b==='L2')value*=2;if(b==='L3')value*=3;if(b==='W2')mult*=2;if(b==='W3')mult*=3}sum+=value}return sum*mult}
    submit(id){this.assertTurn(id);const words=this.validate(),score=words.reduce((n,w)=>n+this.scoreWord(w),0)+(this.state.pending.length===7?50:0),placed=clone(this.state.pending),rack=this.state.racks[id];for(const x of placed){this.state.board[x.row][x.col]={id:x.id,letter:x.letter,value:x.value,blank:x.blank,assignedLetter:x.assignedLetter,owner:id};rack.splice(rack.findIndex(t=>t.id===x.id),1)}while(rack.length<7&&this.state.bag.length)rack.push(this.state.bag.pop());this.state.scores[id]+=score;this.state.history.unshift({playerId:id,score,words:words.map(w=>w.map(x=>x.tile.letter).join('')),placed});this.state.pending=[];this.state.passes=0;this.nextTurn();return{score,words:words.map(w=>w.map(x=>x.tile.letter).join(''))}}
    exchange(id,tileIds){this.assertTurn(id);if(this.state.pending.length)throw new Error('Önce tahtadaki geçici harfleri geri al.');const ids=[...new Set((tileIds||[]).map(String))],rack=this.state.racks[id];if(!ids.length)throw new Error('Değiştirilecek en az bir harf seç.');if(this.state.bag.length<ids.length)throw new Error('Torbada değiştirmek için yeterli harf yok.');const old=ids.map(tileId=>{const tile=rack.find(t=>t.id===tileId);if(!tile)throw new Error('Seçilen harf ıstakanda değil.');return tile});for(const tile of old)rack.splice(rack.findIndex(x=>x.id===tile.id),1);for(let i=0;i<old.length;i++)rack.push(this.state.bag.pop());this.state.bag=shuffle(this.state.bag.concat(old));this.state.passes++;this.state.history.unshift({playerId:id,score:0,words:[`${old.length} HARF DEĞİŞTİ` ]});if(this.state.passes>=this.players.length*2)this.finish();else this.nextTurn();return this.getStateForPlayer(id)}
    pass(id){this.assertTurn(id);this.state.pending=[];this.state.passes++;this.state.history.unshift({playerId:id,score:0,words:['PAS']});if(this.state.passes>=this.players.length*2)this.finish();else this.nextTurn()}
    nextTurn(){if(this.state.bag.length===0&&this.players.some(p=>this.state.racks[p.id].length===0))return this.finish();this.state.turnIndex=(this.state.turnIndex+1)%this.players.length;this.state.turnNumber++}
    finish(){if(this.state.status==='finished')return;const before=clone(this.state.scores),empty=this.players.find(p=>this.state.racks[p.id].length===0),remainders={};for(const p of this.players){remainders[p.id]=this.state.racks[p.id].reduce((n,t)=>n+t.value,0);this.state.scores[p.id]-=remainders[p.id]}if(empty)this.state.scores[empty.id]+=this.players.reduce((n,p)=>p.id===empty.id?n:n+remainders[p.id],0);this.state.status='finished';this.state.finalAdjustments=Object.fromEntries(this.players.map(p=>[p.id,this.state.scores[p.id]-before[p.id]]));this.state.winner=this.players.slice().sort((a,b)=>this.state.scores[b.id]-this.state.scores[a.id]||before[b.id]-before[a.id])[0].id}
    getFullState(){return{...clone(this.state),players:clone(this.players),bonuses:clone(this.bonuses),currentPlayer:clone(this.current())}}
    getStateForPlayer(id){const s=this.getFullState(),stagedIds=new Set(this.state.pending.map(tile=>tile.id));s.yourRack=clone((this.state.racks[id]||[]).filter(tile=>!stagedIds.has(tile.id)));s.rackCounts=Object.fromEntries(this.players.map(p=>[p.id,this.state.racks[p.id].length-(p.id===id?this.state.pending.length:0)]));s.bagCount=this.state.bag.length;delete s.racks;delete s.bag;return s}
  }
  global.SOZCUK=Object.freeze({WordClashGame,LETTERS,SIZE});
})(typeof window!=='undefined'?window:globalThis);
