'use strict';
const{randomUUID}=require('node:crypto');
const{MODE_SEATS}=require('./matchmaker');

class TournamentManager{
  constructor(options={}){this.repository=options.repository;this.createMatch=options.createMatch||(()=>{});this.notify=options.notify||(()=>{});if(!this.repository?.db)throw new Error('Turnuva deposu gerekli.');this.db=this.repository.db;this.migrate();this.seed()}
  migrate(){this.db.exec(`CREATE TABLE IF NOT EXISTS tournaments(id TEXT PRIMARY KEY,title TEXT NOT NULL,mode TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('open','active','finished','cancelled')),capacity INTEGER NOT NULL,entry_fee INTEGER NOT NULL DEFAULT 0,prize_pool INTEGER NOT NULL DEFAULT 0,starts_at INTEGER,champion_id TEXT,created_at INTEGER NOT NULL,finished_at INTEGER);CREATE TABLE IF NOT EXISTS tournament_entries(tournament_id TEXT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id),username TEXT NOT NULL,seed INTEGER,status TEXT NOT NULL DEFAULT 'registered',joined_at INTEGER NOT NULL,PRIMARY KEY(tournament_id,user_id));CREATE TABLE IF NOT EXISTS tournament_games(id TEXT PRIMARY KEY,tournament_id TEXT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,round INTEGER NOT NULL,slot INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN('waiting','playing','finished')),player1_id TEXT,player2_id TEXT,winner_id TEXT,match_id TEXT UNIQUE,created_at INTEGER NOT NULL,finished_at INTEGER,UNIQUE(tournament_id,round,slot));CREATE INDEX IF NOT EXISTS idx_tournament_entries_user ON tournament_entries(user_id,status);CREATE INDEX IF NOT EXISTS idx_tournament_games_match ON tournament_games(match_id);`)}
  seed(){const open=this.db.prepare("SELECT 1 FROM tournaments WHERE status IN('open','active') LIMIT 1").get();if(open)return;this.db.prepare("INSERT INTO tournaments(id,title,mode,status,capacity,entry_fee,prize_pool,starts_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(randomUUID(),'Kantin Tavla Kupası','spvp','open',4,250,5000,null,Date.now())}
  view(id,userId){const tournament=this.db.prepare('SELECT * FROM tournaments WHERE id=?').get(id);if(!tournament)throw new Error('Turnuva bulunamadı.');const entries=this.db.prepare('SELECT user_id AS userId,username,seed,status,joined_at AS joinedAt FROM tournament_entries WHERE tournament_id=? ORDER BY COALESCE(seed,999),joined_at').all(id),games=this.db.prepare('SELECT id,round,slot,status,player1_id AS player1Id,player2_id AS player2Id,winner_id AS winnerId,match_id AS matchId FROM tournament_games WHERE tournament_id=? ORDER BY round,slot').all(id),mine=entries.find(entry=>entry.userId===userId)||null;return{id:tournament.id,title:tournament.title,mode:tournament.mode,status:tournament.status,capacity:tournament.capacity,entryFee:tournament.entry_fee,prizePool:tournament.prize_pool,startsAt:tournament.starts_at,championId:tournament.champion_id,registered:entries.length,entries,games,mine}}
  list(userId){return this.db.prepare("SELECT id FROM tournaments WHERE status<>'cancelled' ORDER BY CASE status WHEN 'active' THEN 0 WHEN 'open' THEN 1 ELSE 2 END,created_at DESC LIMIT 12").all().map(row=>this.view(row.id,userId))}
  activeFor(userId){return this.db.prepare("SELECT e.tournament_id AS tournamentId,e.status FROM tournament_entries e JOIN tournaments t ON t.id=e.tournament_id WHERE e.user_id=? AND t.status IN('open','active') AND e.status IN('registered','active') LIMIT 1").get(userId)||null}
  emit(id){const entries=this.db.prepare('SELECT user_id AS id FROM tournament_entries WHERE tournament_id=?').all(id);for(const entry of entries)this.notify(entry.id,'tournament:update',this.view(id,entry.id))}
  debit(tournament,userId){if(!tournament.entry_fee)return;const user=this.repository.get(userId);if(user.coins<tournament.entry_fee)throw new Error('Turnuva kayıt ücreti için yeterli Kantin Coin yok.');const key=`tournament:${tournament.id}:entry:${userId}`,existing=this.db.prepare('SELECT 1 FROM coin_transactions WHERE idempotency_key=?').get(key);if(existing)return;const balance=user.coins-tournament.entry_fee;this.db.prepare('UPDATE users SET coins=? WHERE id=?').run(balance,userId);this.db.prepare('INSERT INTO coin_transactions VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),userId,-tournament.entry_fee,balance,'tournament_entry',tournament.id,key,Date.now());this.notify(userId,'coins:updated',{balance,delta:-tournament.entry_fee,type:'entry',tournamentId:tournament.id})}
  refund(tournament,userId){if(!tournament.entry_fee)return;const key=`tournament:${tournament.id}:refund:${userId}`,existing=this.db.prepare('SELECT 1 FROM coin_transactions WHERE idempotency_key=?').get(key);if(existing)return;const user=this.repository.get(userId),balance=user.coins+tournament.entry_fee;this.db.prepare('UPDATE users SET coins=? WHERE id=?').run(balance,userId);this.db.prepare('INSERT INTO coin_transactions VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),userId,tournament.entry_fee,balance,'tournament_refund',tournament.id,key,Date.now());this.notify(userId,'coins:updated',{balance,delta:tournament.entry_fee,type:'refund',tournamentId:tournament.id})}
  join(id,userId){const tournament=this.db.prepare('SELECT * FROM tournaments WHERE id=?').get(id);if(!tournament||tournament.status!=='open')throw new Error('Bu turnuvanın kayıtları kapalı.');if(this.db.prepare("SELECT 1 FROM tournament_entries WHERE user_id=? AND status IN('registered','active')").get(userId))throw new Error('Zaten devam eden bir turnuva kaydın var.');const count=this.db.prepare('SELECT count(*) AS n FROM tournament_entries WHERE tournament_id=?').get(id).n;if(count>=tournament.capacity)throw new Error('Turnuva kontenjanı dolu.');const user=this.repository.get(userId);this.db.exec('BEGIN IMMEDIATE');try{this.debit(tournament,userId);this.db.prepare('INSERT INTO tournament_entries(tournament_id,user_id,username,joined_at) VALUES(?,?,?,?)').run(id,user.id,user.username,Date.now());this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}const updated=this.view(id,userId);if(updated.registered===updated.capacity)this.start(id);else this.emit(id);return this.view(id,userId)}
  leave(id,userId){const tournament=this.db.prepare('SELECT * FROM tournaments WHERE id=?').get(id);if(!tournament||tournament.status!=='open')throw new Error('Başlamış turnuvadan kayıt silinemez.');const removed=this.db.prepare('DELETE FROM tournament_entries WHERE tournament_id=? AND user_id=?').run(id,userId);if(!removed.changes)throw new Error('Bu turnuvaya kayıtlı değilsin.');this.refund(tournament,userId);this.emit(id);return this.view(id,userId)}
  start(id){const tournament=this.db.prepare('SELECT * FROM tournaments WHERE id=?').get(id),entries=this.db.prepare('SELECT user_id AS userId,username FROM tournament_entries WHERE tournament_id=? ORDER BY joined_at,user_id').all(id);if(!tournament||tournament.status!=='open'||entries.length!==tournament.capacity)return;this.db.prepare("UPDATE tournaments SET status='active' WHERE id=?").run(id);entries.forEach((entry,index)=>this.db.prepare("UPDATE tournament_entries SET seed=?,status='active' WHERE tournament_id=? AND user_id=?").run(index+1,id,entry.userId));for(let slot=0;slot<entries.length/2;slot++)this.createGame(tournament,1,slot,entries[slot*2],entries[slot*2+1]);this.emit(id)}
  createGame(tournament,round,slot,a,b){const gameId=randomUUID(),matchId=randomUUID(),seats=MODE_SEATS[tournament.mode];if(!seats||seats.length!==2)throw new Error('Turnuva modu iki oyunculu olmalı.');this.db.prepare("INSERT INTO tournament_games(id,tournament_id,round,slot,status,player1_id,player2_id,match_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(gameId,tournament.id,round,slot,'playing',a.userId,b.userId,matchId,Date.now());const players=[a,b].map((entry,index)=>{const user=this.repository.get(entry.userId);return{id:user.id,username:user.username,avatarUrl:user.avatarUrl,seat:seats[index],team:null,isBot:false,level:user.level}}),match={matchId,mode:tournament.mode,wordLocale:null,stake:0,pot:0,tournamentId:tournament.id,tournamentRound:round,players};this.createMatch(match);for(const player of players)this.notify(player.id,'match:found',{...match,assignment:player});return match}
  winnerFor(room,result){const keys=new Set([result?.winnerPlayerId,result?.winnerTeam,result?.winner,...(result?.winners||[])].filter(Boolean));return room.players.find(player=>keys.has(player.id)||keys.has(player.seat)||keys.has(player.team))?.id||null}
  advance(room,result){const game=this.db.prepare('SELECT * FROM tournament_games WHERE match_id=?').get(room.id);if(!game||game.status==='finished')return null;const winnerId=this.winnerFor(room,result);if(!winnerId)throw new Error('Turnuva maçının kazananı belirlenemedi.');this.db.prepare("UPDATE tournament_games SET status='finished',winner_id=?,finished_at=? WHERE id=?").run(winnerId,Date.now(),game.id);const loserId=game.player1_id===winnerId?game.player2_id:game.player1_id;this.db.prepare("UPDATE tournament_entries SET status='eliminated' WHERE tournament_id=? AND user_id=?").run(game.tournament_id,loserId);const tournament=this.db.prepare('SELECT * FROM tournaments WHERE id=?').get(game.tournament_id),rounds=Math.log2(tournament.capacity);if(game.round>=rounds){this.db.prepare("UPDATE tournaments SET status='finished',champion_id=?,finished_at=? WHERE id=?").run(winnerId,Date.now(),tournament.id);this.db.prepare("UPDATE tournament_entries SET status=CASE WHEN user_id=? THEN 'champion' ELSE 'eliminated' END WHERE tournament_id=?").run(winnerId,tournament.id);this.award(tournament,winnerId);this.emit(tournament.id);this.seed();return this.view(tournament.id,winnerId)}const siblingSlot=game.slot%2===0?game.slot+1:game.slot-1,sibling=this.db.prepare("SELECT * FROM tournament_games WHERE tournament_id=? AND round=? AND slot=? AND status='finished'").get(tournament.id,game.round,siblingSlot);if(sibling){const parentSlot=Math.floor(game.slot/2),exists=this.db.prepare('SELECT 1 FROM tournament_games WHERE tournament_id=? AND round=? AND slot=?').get(tournament.id,game.round+1,parentSlot);if(!exists){const first=game.slot<sibling.slot?winnerId:sibling.winner_id,second=game.slot<sibling.slot?sibling.winner_id:winnerId,a=this.db.prepare('SELECT user_id AS userId,username FROM tournament_entries WHERE tournament_id=? AND user_id=?').get(tournament.id,first),b=this.db.prepare('SELECT user_id AS userId,username FROM tournament_entries WHERE tournament_id=? AND user_id=?').get(tournament.id,second);this.createGame(tournament,game.round+1,parentSlot,a,b)}}this.emit(tournament.id);return this.view(tournament.id,winnerId)}
  award(tournament,userId){const key=`tournament:${tournament.id}:prize:${userId}`,existing=this.db.prepare('SELECT 1 FROM coin_transactions WHERE idempotency_key=?').get(key);if(existing||!tournament.prize_pool)return;const user=this.repository.get(userId),balance=user.coins+tournament.prize_pool;this.db.prepare('UPDATE users SET coins=? WHERE id=?').run(balance,userId);this.db.prepare('INSERT INTO coin_transactions VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),userId,tournament.prize_pool,balance,'tournament_prize',tournament.id,key,Date.now());this.notify(userId,'coins:updated',{balance,delta:tournament.prize_pool,type:'payout',tournamentId:tournament.id})}
}
module.exports={TournamentManager};
