'use strict';
const{randomInt}=require('node:crypto');require('../src/spvp.js');require('../src/upvp.js');require('../src/pisti.js');require('../src/okey101.js');require('../src/batak.js');global.KANTIN_TURKISH_WORDS=require('../assets/data/turkish-words.json');require('../src/word-language-packs.js');require('../src/sozcuk.js');
const die=()=>randomInt(1,7);const clone=value=>structuredClone(value);const point=value=>{if(value==='bar'||value==='off')return value;const n=Number(value);if(!Number.isInteger(n)||n<0||n>23)throw new Error('Geçersiz tavla hanesi.');return n};
class GameRoom{
  constructor(match,options={}){this.id=match.matchId;this.mode=match.mode;this.stake=Number(match.stake)||0;this.tournamentId=match.tournamentId||null;this.wordLocale=this.mode==='sozcukDuel'?KANTIN_WORD_LANGUAGES.normalizeLocale(match.wordLocale||match.state?.wordLocale||'tr'):null;this.players=match.players.map(clone);this.send=options.send||(()=>{});this.repository=options.repository||null;this.onFinished=options.onFinished||null;this.manageClock=options.manageClock!==false;this.createdAt=match.createdAt||Date.now();this.lastActivity=match.updatedAt||this.createdAt;this.version=match.version||0;this.status=match.status||'playing';this.processed=new Map(this.players.map(p=>[p.id,new Map()]));this.turnTimer=null;this.clockKeyActive=null;this.timeoutCounts=new Map();this.botPlayers=new Set(this.players.filter(player=>player.isBot||String(player.id).startsWith('BOT-')).map(player=>player.id));this.engine=this.createEngine();if(match.state){this.restoreEngine(match.state);for(const player of this.players)this.timeoutCounts.set(player.id,Number(match.state.timeoutCounts?.[player.seat]||0));this.botPlayers=new Set([...this.botPlayers,...(Array.isArray(match.state.botPlayers)?match.state.botPlayers:[])])}if(this.engine.state)this.engine.state.botPlayers=[...this.botPlayers];if(!match.state)this.repository?.recordMatch({...match,stake:this.stake,wordLocale:this.wordLocale,state:this.fullState(),version:this.version});this.armClock()}
  createEngine(){switch(this.mode){case'spvp':return new SPVP.StandardBackgammonPvP();case'upvp':return new UPVP.UniversityBackgammonPvP({players:this.players.map(p=>({id:p.seat,username:p.username,team:p.team,boardId:p.seat.endsWith('1')?'board1':'board2'}))});case'pistiSolo':return new PISTI.PistiGame({mode:'solo',players:this.players.map(p=>({id:p.seat,username:p.username}))});case'pistiTeam':return new PISTI.PistiGame({mode:'team',players:this.players.map(p=>({id:p.seat,username:p.username,team:p.team}))});case'okeySolo':return new OKEY101.Okey101Game({mode:'solo',players:this.players.map(p=>({id:p.seat,username:p.username}))});case'okeyTeam':return new OKEY101.Okey101Game({mode:'team',players:this.players.map(p=>({id:p.seat,username:p.username,team:p.team}))});case'batakKozMaca':return new BATAK.BatakGame({mode:'kozMaca',players:this.players.map(p=>({id:p.seat,username:p.username,team:p.team}))});case'batakGommeli':return new BATAK.BatakGame({mode:'gommedi',players:this.players.map(p=>({id:p.seat,username:p.username,team:p.team}))});case'sozcukDuel':return new SOZCUK.WordClashGame({language:this.wordLocale,players:this.players.map(p=>({id:p.seat,username:p.username}))});default:throw new Error('Desteklenmeyen oyun modu.')}}
  fullState(){if(this.mode==='spvp')return this.engine.getState();if(this.mode==='upvp')return this.engine.getState();return this.engine.getFullState()}
  restoreEngine(snapshot){if(this.mode==='spvp')this.engine.loadState(snapshot);else if(this.mode==='upvp')this.engine.loadState(snapshot);else{if(snapshot.players)this.engine.players=clone(snapshot.players);if(snapshot.rules)this.engine.rules=clone(snapshot.rules);const state=clone(snapshot);delete state.players;delete state.rules;this.engine.state=state}}
  player(userId){const p=this.players.find(x=>x.id===userId);if(!p)throw new Error('Bu maçın oyuncusu değilsin.');return p}
  turnId(){return `${this.id}:${this.version}`}
  stateFor(userId){const p=this.player(userId);let state;if(this.mode==='spvp')state=this.engine.getState();else if(this.mode==='upvp')state=this.engine.getState();else state=this.engine.getStateForPlayer(p.seat);return{matchId:this.id,mode:this.mode,wordLocale:this.wordLocale,seat:p.seat,turnId:this.turnId(),status:this.status,state}}
  sync(userId){this.send(userId,'game:state',this.stateFor(userId))}
  broadcast(){for(const p of this.players)if(!this.botPlayers.has(p.id))this.sync(p.id)}
  upvpBotPlayer(){if(this.mode!=='upvp'||this.engine.match.status!=='playing')return null;if(!this.engine.match.sharedRollOpen)return this.engine.getCurrentRollerId();const activeTeam=this.engine.match.activeTeam;return this.players.find(player=>player.team===activeTeam&&this.botPlayers.has(player.id)&&this.engine.match.boardRollStatus[player.seat.endsWith('1')?'board1':'board2']==='playing')?.seat||null}
  clockKey(){if(this.status!=='playing')return null;if(this.mode==='upvp'){if(this.engine.match.status!=='playing')return null;const player=this.upvpBotPlayer();if(!player||!this.botPlayers.has(this.players.find(item=>item.seat===player)?.id))return null;return this.engine.match.sharedRollOpen?`upvp-move:${this.engine.match.round}:${this.engine.match.sharedRollId}:${player}:${this.engine.getLegalMovesForPlayer(player).length}:${this.engine.boards[this.engine.players[player].boardId].state.remainingDice.join(',')}`:`upvp-roll:${this.engine.match.round}:${this.engine.match.activeTeam}:${player}`}if(this.engine.state?.status!=='playing')return null;const s=this.engine.state;if(this.mode==='spvp'){if(!s.openingComplete){const bot=this.players.find(player=>this.botPlayers.has(player.id)&&s.openingRolls?.[player.seat]==null);return bot?`opening:${s.openingRolls?.white??'-'}:${s.openingRolls?.black??'-'}:${bot.seat}`:null}if(s.pendingDouble)return`double:${s.turnNumber}:${s.pendingDouble.from}:${s.pendingDouble.to}:${s.pendingDouble.proposedValue}`;return`turn:${s.turnNumber}:${s.turn}`}if(this.mode.startsWith('pisti'))return s.pendingBluff?`bluff:${s.moveNumber}:${s.pendingBluff.responderId}`:`turn:${s.moveNumber}:${this.engine.getCurrentPlayer().id}`;if(this.mode.startsWith('okey'))return`turn:${s.turnNumber}:${this.engine.getCurrentPlayer().id}`;if(this.mode.startsWith('batak'))return!s.trump?`trump-select:${s.trumpSelector}`:`turn:${s.trickNumber}:${this.engine.getCurrentPlayer().id}`;if(this.mode==='sozcukDuel')return`turn:${s.turnNumber}:${this.engine.current().id}`;return null}
  clockPlayer(){if(this.mode==='upvp')return this.upvpBotPlayer();const s=this.engine.state;if(this.mode==='spvp'){if(!s.openingComplete)return this.players.find(player=>this.botPlayers.has(player.id)&&s.openingRolls?.[player.seat]==null)?.seat||s.turn;return s.pendingDouble?.to||s.turn}if(this.mode.startsWith('pisti'))return s.pendingBluff?.responderId||this.engine.getCurrentPlayer().id;if(this.mode.startsWith('batak'))return!s.trump?s.trumpSelector:this.engine.getCurrentPlayer().id;if(this.mode==='sozcukDuel')return this.engine.current().id;return this.engine.getCurrentPlayer().id}
  botThinkDelay(seat){return this.botDifficultyForSeat(seat)==='İYİ'?randomInt(950,1851):randomInt(1350,2451)}
  turnDeadline(){return Number(this.mode==='upvp'?this.engine.match.turnDeadlineAt:this.engine.state?.turnDeadlineAt)||0}
  setTurnDeadline(deadline){if(this.mode==='spvp')this.engine.setTurnDeadline(deadline);else if(this.mode==='upvp')this.engine.match.turnDeadlineAt=deadline;else this.engine.state.turnDeadlineAt=deadline}
  armClock(fresh=false){const key=this.clockKey();if(!fresh&&key===this.clockKeyActive&&this.turnTimer)return;clearTimeout(this.turnTimer);this.turnTimer=null;this.clockKeyActive=key;if(!key){if(this.mode==='spvp')this.engine.setTurnDeadline(null);else if(this.mode==='upvp')this.engine.match.turnDeadlineAt=null;return}const seat=this.clockPlayer(),member=this.players.find(p=>p.seat===seat),automatic=member&&this.botPlayers.has(member.id),existing=this.turnDeadline(),keepExisting=!fresh&&existing>0&&(!this.manageClock||existing>Date.now()),deadline=keepExisting?existing:(automatic?Date.now()+this.botThinkDelay(seat):Date.now()+20000);this.setTurnDeadline(deadline);if(!this.manageClock)return;this.turnTimer=setTimeout(()=>{try{this.handleTimeout(key)}catch(error){console.error('Bot turu tamamlanamadı',{matchId:this.id,mode:this.mode,message:error.message});this.clockKeyActive=null;this.armClock(true)}},Math.max(1,deadline-Date.now()+15));this.turnTimer.unref?.()}
  botDifficultyForSeat(seat){const player=this.players.find(item=>item.seat===seat);return player?.botDifficulty==='İYİ'||String(player?.id).startsWith('BOT-IYI-')?'İYİ':'ORTA'}
  botCompleteSpvpTurn(player){let guard=12;if(this.engine.state.turn!==player||this.engine.state.status!=='playing')return;if(!this.engine.state.remainingDice.length)this.engine.setDice(die(),die());const good=this.botDifficultyForSeat(player)==='İYİ';while(this.engine.state.status==='playing'&&this.engine.state.turn===player&&guard-->0){const moves=this.engine.getLegalMoves();if(!moves.length){this.engine.endTurn({reason:'timeout-bot-no-move'});break}const move=good?moves.slice().sort((a,b)=>this.scoreTavlaMove(player,b)-this.scoreTavlaMove(player,a))[0]:moves[randomInt(moves.length)];this.engine.move(move.from,move.to,move.die)}}
  scoreTavlaMove(player,move){if(move.to==='off')return 100;const point=this.engine.state.points?.[Number(move.to)],hit=point?.owner&&point.owner!==player&&point.count===1;return(hit?35:0)+(typeof move.from==='number'?Math.abs(Number(move.to)-move.from):20)}
  botCompleteUpvpTurn(player){if(!this.engine.match.sharedRollOpen){this.engine.setSharedDice(die(),die(),player,`bot-roll-${this.version+1}`);return}const moves=this.engine.getLegalMovesForPlayer(player);if(!moves.length){this.engine.syncSharedTurnProgress();return}const member=this.players.find(item=>item.seat===player),good=this.botDifficultyForSeat(player)==='İYİ',board=this.engine.boards[this.engine.players[player].boardId];const score=move=>{if(move.to==='off')return 100;const target=board.state.points?.[Number(move.to)],hit=target?.owner&&target.owner!==this.engine.players[player].color&&target.count===1;return(hit?35:0)+(typeof move.from==='number'?Math.abs(Number(move.to)-move.from):20)+(member?.team===this.engine.match.activeTeam?1:0)};const move=good?moves.slice().sort((a,b)=>score(b)-score(a))[0]:moves[randomInt(moves.length)];this.engine.move(player,move.from,move.to,move.die)}
  choosePistiCard(player,good){const hand=this.engine.getHand(player);if(!good||hand.length<2)return hand[randomInt(hand.length)];const table=this.engine.state.table||[],top=table.at(-1),pointValue=card=>(card.rank==='A'||card.rank==='J'?1:0)+(card.rank==='2'&&card.suit==='clubs'?2:0)+(card.rank==='10'&&card.suit==='diamonds'?3:0);return hand.slice().sort((a,b)=>{const score=card=>{const captures=top&&(card.rank===top.rank||card.rank==='J');return(captures?table.length*4+table.reduce((sum,item)=>sum+pointValue(item),0)+(table.length===1&&card.rank!=='J'?10:0):0)-pointValue(card)*1.5-(card.rank==='J'&&!captures?3:0)};return score(b)-score(a)})[0]}
  okeyTileUtility(tile,hand){let score=tile.isFalseJoker?2:0;for(const other of hand){if(other.id===tile.id)continue;if(other.number===tile.number)score+=2;if(other.color===tile.color&&Math.abs(Number(other.number)-Number(tile.number))<=2)score+=3-Math.abs(Number(other.number)-Number(tile.number))}return score}
  botCompleteTableTurn(player){const good=this.botDifficultyForSeat(player)==='İYİ';if(this.mode.startsWith('pisti')){const pending=this.engine.state.pendingBluff;if(pending){const honest=pending.card.rank===pending.baseCard.rank;this.engine.resolveBluff(player,good?honest:Math.random()<.58);return}const hand=this.engine.getHand(player);if(!hand.length)return;const card=this.choosePistiCard(player,good),top=this.engine.state.table?.at(-1),canBluff=this.engine.state.table?.length===1&&card.rank!==top?.rank&&card.rank!=='J';if(canBluff&&Math.random()<(good?.18:.08))this.engine.declareBluff(player,card.id);else this.engine.playCard(player,card.id);return}if(this.mode.startsWith('okey')){if(this.engine.state.phase==='draw')this.engine.drawFromStock(player);if(this.engine.state.status!=='playing')return;if(good){try{if(!this.engine.state.opened?.[player]&&this.engine.openingPotential(player).points>=this.engine.openingTarget(player))this.engine.autoOpenMelds(player);else if(this.engine.state.opened?.[player])this.engine.autoLayoff(player)}catch{}}const hand=this.engine.state.hands[player];if(hand.length){const tile=good?hand.slice().sort((a,b)=>this.okeyTileUtility(a,hand)-this.okeyTileUtility(b,hand))[0]:hand[randomInt(hand.length)];this.engine.discard(player,tile.id)}return}if(this.mode.startsWith('batak')){if(!this.engine.state.trump){const suits=['clubs','diamonds','hearts','spades'];this.engine.selectTrump(player,suits[randomInt(suits.length)]);return}const hand=this.engine.getHand(player);if(!hand.length)return;const validCards=hand.filter(card=>this.engine.isValidMove(player,card));if(validCards.length) this.engine.playCard(player,validCards[randomInt(validCards.length)].id);return}if(this.mode==='sozcukDuel'){const rack=this.engine.state.racks[player]||[];if(good&&this.engine.state.bag.length>=2&&rack.length>=2)this.engine.exchange(player,rack.slice().sort((a,b)=>b.value-a.value).slice(0,2).map(tile=>tile.id));else this.engine.pass(player)}}
  handleTimeout(expectedKey){if(expectedKey!==this.clockKey()||this.status!=='playing')return;const player=this.clockPlayer(),member=this.players.find(p=>p.seat===player),automatic=member&&this.botPlayers.has(member.id);if(this.mode==='upvp'){if(!automatic)return;this.botCompleteUpvpTurn(player)}else if(this.mode==='spvp'){if(!this.engine.state.openingComplete&&automatic)this.engine.submitOpeningRoll(player,die());else if(automatic){if(this.engine.state.pendingDouble)this.engine.acceptDouble(player);else this.botCompleteSpvpTurn(player)}else{const count=this.engine.registerTimeout(player);if(this.engine.state.pendingDouble)this.engine.declineDouble(player);else if(count>=2)this.engine.finishForfeit(player==='white'?'black':'white',player,'timeout-forfeit',this.engine.state.cubeValue);else this.botCompleteSpvpTurn(player)}}else{const count=(this.timeoutCounts.get(member.id)||0)+1;this.timeoutCounts.set(member.id,count);this.engine.state.timeoutCounts=Object.fromEntries(this.players.map(p=>[p.seat,this.timeoutCounts.get(p.id)||0]));if(count>=2&&!this.botPlayers.has(member.id)){this.botPlayers.add(member.id);member.isBot=true;member.botDifficulty=member.botDifficulty||'ORTA';this.repository?.updateMatchPlayers(this.id,this.players);this.send(member.id,'game:kicked',{matchId:this.id,reason:'İki kez süre dolduğu için koltuğu bot devraldı.'})}this.engine.state.botPlayers=[...this.botPlayers];this.botCompleteTableTurn(player)}this.version++;this.lastActivity=Date.now();this.clockKeyActive=null;this.repository?.updateMatchState(this.id,this.fullState(),this.version);this.refreshStatus();this.broadcast();this.armClock(true)}
  remember(userId,actionId,result){const map=this.processed.get(userId);map.set(actionId,result);if(map.size>250)map.delete(map.keys().next().value)}
  act(userId,request){
    if(this.status!=='playing')throw new Error('Maç tamamlanmış.');
    if(this.botPlayers.has(userId))throw new Error('Bu koltuğu oyun sonuna kadar bot devraldı.');
    const player=this.player(userId),actionId=String(request?.actionId||'');
    if(!/^[a-zA-Z0-9-]{8,80}$/.test(actionId))throw new Error('Geçersiz actionId.');
    const previous=this.processed.get(userId).get(actionId);
    if(previous){this.send(userId,'game:ack',{...previous,duplicate:true});return previous}
    if(request.turnId!==this.turnId())throw new Error('State güncel değil; yeni oyun durumu gönderildi.');
    try{
      this.apply(player,request.action,request.payload||{});
    }catch(error){
      // 101'de geçersiz açılış gerçek bir +101 cezasıdır; aksiyon reddedilse
      // bile değişen ceza durumu bütün istemcilere ve kalıcı kayda gönderilir.
      if(error.penaltyApplied){
        this.version++;
        this.lastActivity=Date.now();
        this.repository?.updateMatchState(this.id,this.fullState(),this.version);
        this.broadcast();
      }
      throw error;
    }
    this.version++;
    this.lastActivity=Date.now();
    this.clockKeyActive=null;
    this.armClock(true);
    this.repository?.updateMatchState(this.id,this.fullState(),this.version);
    this.refreshStatus();
    const result={actionId,turnId:this.turnId(),accepted:true};
    this.remember(userId,actionId,result);
    this.send(userId,'game:ack',result);
    this.broadcast();
    return result
  }
  apply(player,action,payload){if(this.mode==='spvp')return this.applySpvp(player,action,payload);if(this.mode==='upvp')return this.applyUpvp(player,action,payload);if(this.mode.startsWith('pisti'))return this.applyPisti(player,action,payload);if(this.mode.startsWith('okey'))return this.applyOkey(player,action,payload);if(this.mode.startsWith('batak'))return this.applyBatak(player,action,payload);return this.applyWord(player,action,payload)}
  applySpvp(player,action,payload){if(!this.engine.state.openingComplete){if(action!=='roll')throw new Error('Önce başlangıç zarları atılmalı.');return this.engine.submitOpeningRoll(player.seat,die())}if(action==='doubleAccept')return this.engine.acceptDouble(player.seat);if(action==='doubleDecline')return this.engine.declineDouble(player.seat);if(this.engine.state.turn!==player.seat)throw new Error('Sıra sende değil.');if(action==='doubleOffer')return this.engine.offerDouble(player.seat);if(this.engine.state.pendingDouble)throw new Error('Katlama teklifi cevap bekliyor.');if(action==='roll')return this.engine.setDice(die(),die());if(action==='move')return this.engine.move(point(payload.from),point(payload.to),payload.die??null);if(action==='moveCombined')return this.engine.moveCombined(point(payload.from),point(payload.to));throw new Error('Geçersiz Tavla aksiyonu.')}
  applyUpvp(player,action,payload){if(action==='roll')return this.engine.setSharedDice(die(),die(),player.seat,`roll-${this.version+1}`);if(action==='move')return this.engine.move(player.seat,point(payload.from),point(payload.to),payload.die??null);throw new Error('Geçersiz Üniversite Tavlası aksiyonu.')}
  applyPisti(player,action,payload){if(action==='play')return this.engine.playCard(player.seat,String(payload.cardId||''));if(action==='bluff')return this.engine.declareBluff(player.seat,String(payload.cardId||''));if(action==='bluff-believe')return this.engine.resolveBluff(player.seat,true);if(action==='bluff-challenge')return this.engine.resolveBluff(player.seat,false);throw new Error('Geçersiz Pişti aksiyonu.')}
  applyOkey(player,action,payload){const id=player.seat;if(action==='draw')return this.engine.drawFromStock(id);if(action==='take')return this.engine.takeDiscard(id);if(action==='returnDiscard')return this.engine.returnTakenDiscard(id);if(action==='openMelds')return this.engine.openMelds(id,payload.groups);if(action==='openPairs')return this.engine.openPairs(id,payload.groups);if(action==='autoOpenMelds')return this.engine.autoOpenMelds(id);if(action==='autoOpenPairs')return this.engine.autoOpenPairs(id);if(action==='autoLayoff')return this.engine.autoLayoff(id);if(action==='addToMeld')return this.engine.addToMeld(id,payload.ownerId,payload.meldId,payload.tileIds);if(action==='retrieveOkey')return this.engine.retrieveOkey(id,payload.ownerId,payload.meldId,payload.replacementTileId);if(action==='discard')return this.engine.discard(id,String(payload.tileId||''));throw new Error('Geçersiz 101 aksiyonu.')}
  applyBatak(player,action,payload){const id=player.seat;if(action==='selectTrump')return this.engine.selectTrump(id,String(payload.suit||''));if(action==='play')return this.engine.playCard(id,String(payload.cardId||''));throw new Error('Geçersiz Batak aksiyonu.')}
  applyWord(player,action,payload){const id=player.seat;if(action==='stage')return this.engine.stage(id,String(payload.tileId||''),payload.row,payload.col,payload.blankLetter);if(action==='unstage')return this.engine.unstage(id,payload.row,payload.col);if(action==='recall')return this.engine.recall(id);if(action==='submit')return this.engine.submit(id);if(action==='exchange')return this.engine.exchange(id,payload.tileIds);if(action==='pass')return this.engine.pass(id);throw new Error('Geçersiz Sözcük Kapışması aksiyonu.')}
  refreshStatus(){let finished=false,result=null;if(this.mode==='spvp'){finished=this.engine.state.status==='finished';result=finished?this.engine.getGameResult():null}else if(this.mode==='upvp'){finished=this.engine.match.status==='finished';result=finished?{winnerTeam:this.engine.match.winnerTeam,score:this.engine.match.score}:null}else{finished=this.engine.state.status==='finished';result=finished?(this.mode.startsWith('pisti')?{winner:this.engine.state.winner,winners:this.engine.state.winners,score:this.engine.state.score}:this.mode==='sozcukDuel'?{winnerPlayerId:this.engine.state.winner,scores:this.engine.state.scores}:{winnerPlayerId:this.engine.state.winnerPlayerId,winnerTeam:this.mode==='okeyTeam'?this.engine.players.find(player=>player.id===this.engine.state.winnerPlayerId)?.team||null:null,scores:this.engine.state.scores}):null}if(finished&&this.status!=='finished'){this.status='finished';const settlements=this.repository?.finishMatch(this.id,result)||{};for(const p of this.players)this.send(p.id,'game:finished',{matchId:this.id,result,coin:settlements[p.id]||null,tournamentId:this.tournamentId});if(this.onFinished)setTimeout(()=>this.onFinished(this,result),0)}}
  setConnected(userId,connected){const p=this.player(userId);if(typeof this.engine.setPlayerConnected==='function')this.engine.setPlayerConnected(p.seat,connected);this.lastActivity=Date.now()}
  replaceWithBot(userId){const p=this.player(userId);this.botPlayers.add(p.id);p.isBot=true;p.botDifficulty=p.botDifficulty||'ORTA';if(this.engine.state)this.engine.state.botPlayers=[...this.botPlayers];this.lastActivity=Date.now();this.clockKeyActive=null;this.repository?.updateMatchPlayers(this.id,this.players);this.repository?.updateMatchState(this.id,this.fullState(),this.version);this.armClock(true)}
}
class GameRoomManager{
  constructor(options={}){this.rooms=new Map();this.byUser=new Map();this.send=options.send||(()=>{});this.repository=options.repository||null;this.onFinished=options.onFinished||null}
  create(match){const room=new GameRoom(match,{send:this.send,repository:this.repository,onFinished:this.onFinished});this.rooms.set(room.id,room);for(const p of match.players)this.byUser.set(p.id,room.id);return room}
  restore(matches){return matches.map(match=>this.create(match))}
  get(id){const room=this.rooms.get(id);if(!room)throw new Error('Oyun odası bulunamadı.');return room}
  forUser(userId){const id=this.byUser.get(userId);return id?this.rooms.get(id)||null:null}
  releaseUser(userId){const room=this.forUser(userId);if(!room)return false;room.replaceWithBot(userId);this.byUser.delete(userId);return true}
  remove(id){const room=this.rooms.get(id);if(!room)return false;for(const p of room.players)this.byUser.delete(p.id);return this.rooms.delete(id)}
  cleanup(finishedIdleMs=300000,activeIdleMs=86400000){const now=Date.now();for(const room of this.rooms.values()){if(room.status==='finished'&&now-room.lastActivity>finishedIdleMs)this.remove(room.id);else if(room.status==='playing'&&now-room.lastActivity>activeIdleMs){this.repository?.abandonMatch(room.id);this.remove(room.id)}}}
}
module.exports={GameRoom,GameRoomManager};
