'use strict';
const http=require('node:http');const path=require('node:path');const fs=require('node:fs');const{randomUUID}=require('node:crypto');const{WebSocketServer,WebSocket}=require('ws');const{Matchmaker}=require('./matchmaker');const{UserRegistry}=require('./user-registry');const{GameRoomManager}=require('./game-room');const publicConfig=require('../api/config');
const root=path.resolve(__dirname,'..');const port=Number(process.env.PORT||4173),isVercel=Boolean(process.env.VERCEL),databasePath=process.env.DATABASE_PATH||(isVercel?path.join('/tmp','kantin.sqlite'):path.join(root,'data','kantin.sqlite'));const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.woff2':'font/woff2','.mp3':'audio/mpeg','.ogg':'audio/ogg'};const allowedOrigins=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
const securityHeaders={'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' ws: wss: https://*.supabase.co; img-src 'self' data: https:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,`http://${req.headers.host}`).pathname);if(pathname==='/api/ws'||pathname==='/ws'){res.writeHead(426,{...securityHeaders,'content-type':'application/json; charset=utf-8','cache-control':'no-store','upgrade':'websocket'}).end(JSON.stringify({ok:false,error:'websocket_upgrade_required'}));return}if(pathname==='/api/config'){for(const[name,value]of Object.entries(securityHeaders))res.setHeader(name,value);publicConfig(req,res);return}const relative=pathname==='/'?'index.html':pathname.slice(1);const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)){res.writeHead(403,securityHeaders).end('Forbidden');return}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404,securityHeaders).end('Not found');return}res.writeHead(200,{...securityHeaders,'content-type':types[path.extname(file)]||'application/octet-stream','cache-control':'no-store'});res.end(data)})});
function websocketRequestAllowed(request){const pathname=new URL(request.url,`http://${request.headers.host||'localhost'}`).pathname;if(pathname!=='/ws'&&pathname!=='/api/ws')return false;const origin=String(request.headers.origin||'');if(!origin)return true;if(allowedOrigins.length)return allowedOrigins.includes(origin);const host=String(request.headers['x-forwarded-host']||request.headers.host||'');return Boolean(host)&&(origin===`https://${host}`||origin===`http://${host}`)}
const wss=new WebSocketServer({noServer:true,maxPayload:16*1024});server.on('upgrade',(request,socket,head)=>{if(!websocketRequestAllowed(request)){socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');socket.destroy();return}wss.handleUpgrade(request,socket,head,ws=>wss.emit('connection',ws,request))});const matchmaker=new Matchmaker();const registry=new UserRegistry({file:databasePath});const connections=new Set();const online=new Map();const sendRaw=(ws,type,payload={})=>ws.readyState===WebSocket.OPEN&&ws.send(JSON.stringify({type,payload}));const sendClient=(client,type,payload)=>sendRaw(client.ws,type,payload);const sendUser=(id,type,payload)=>{const c=online.get(id);if(c)sendClient(c,type,payload)};const isOnline=id=>online.has(id);const gameRooms=new GameRoomManager({send:sendUser,repository:registry});gameRooms.restore(registry.activeMatches());
function emitFriends(userId){const client=online.get(userId);if(client)sendClient(client,'friends:state',registry.view(userId,isOnline))}
function emitRelated(userId){emitFriends(userId);const view=registry.view(userId);[...view.friends,...view.incoming,...view.outgoing].forEach(p=>emitFriends(p.id))}
function broadcast(type,payload,targets=connections){for(const client of targets)sendClient(client,type,payload)}function broadcastStats(){broadcast('lobby:stats',matchmaker.stats())}
function consume(client,bucket,limit,windowMs){const now=Date.now(),list=client.rate[bucket].filter(t=>now-t<windowMs);if(list.length>=limit)throw new Error('Çok hızlı işlem yapıyorsun; kısa süre bekle.');list.push(now);client.rate[bucket]=list}
function sendChat(client,payload){consume(client,'chat',10,10000);const text=String(payload?.text||'').trim().slice(0,300);if(!text)throw new Error('Boş mesaj gönderilemez.');const scope=payload?.room==='match'?'match':'lobby';let targets=connections,roomId='lobby';if(scope==='match'){const room=gameRooms.forUser(client.id);if(!room)throw new Error('Aktif eşleşme odan yok.');targets=room.players.map(p=>online.get(p.id)).filter(Boolean);roomId=room.id}const message={id:randomUUID(),room:scope,roomId,userId:client.id,username:client.username,text,sentAt:Date.now()};registry.recordChat(message);broadcast('chat:message',message,targets)}
function createRooms(matches){for(const match of matches){const room=gameRooms.create(match);for(const player of match.players){const member=online.get(player.id);if(member){member.matchId=room.id;sendClient(member,'chat:history',{room:'match',roomId:room.id,messages:registry.chatHistory(room.id)});room.sync(player.id)}}}}
function handleAuthenticated(client,message){const payload=message.payload||{};consume(client,'actions',60,10000);switch(message.type){case'profile:get':sendClient(client,'profile:data',registry.publicProfile(payload.userId,isOnline));break;case'queue:join':if(gameRooms.forUser(client.id))throw new Error('Devam eden bir maçın var.');createRooms(matchmaker.join(client,payload.mode));broadcastStats();break;case'queue:leave':matchmaker.leave(client.id);broadcastStats();break;case'game:action':{const room=gameRooms.get(payload.matchId);room.act(client.id,payload);break}case'game:sync':{const room=gameRooms.forUser(client.id);if(room)room.sync(client.id);break}case'friend:add':registry.request(client.id,payload.userId);emitRelated(client.id);emitRelated(String(payload.userId).toUpperCase());break;case'friend:accept':registry.accept(client.id,payload.userId);emitRelated(client.id);emitRelated(String(payload.userId).toUpperCase());break;case'friend:remove':registry.remove(client.id,payload.userId);emitRelated(client.id);emitRelated(String(payload.userId).toUpperCase());break;case'chat:send':sendChat(client,payload);break;default:throw new Error('Bilinmeyen mesaj türü.')}}
wss.on('connection',ws=>{const client={connectionId:randomUUID(),id:null,username:'Oyuncu',matchId:null,ws,alive:true,rate:{actions:[],chat:[]},send:(type,payload)=>sendRaw(ws,type,payload)};connections.add(client);sendRaw(ws,'socket:ready',{});ws.on('pong',()=>{client.alive=true});
  ws.on('message',raw=>{try{const message=JSON.parse(raw.toString());if(!message||typeof message.type!=='string')throw new Error('Geçersiz mesaj.');if(message.type==='hello'){const user=registry.authenticate(message.payload?.token,message.payload?.username);client.id=user.id;client.username=user.username;const previous=online.get(user.id);if(previous&&previous!==client)previous.ws.close(4001,'Yeni oturum açıldı');online.set(user.id,client);sendClient(client,'identity',{...registry.view(user.id,isOnline),authToken:user.authToken,stats:matchmaker.stats()});sendClient(client,'chat:history',{room:'lobby',messages:registry.chatHistory('lobby')});emitRelated(user.id);const room=gameRooms.forUser(user.id);if(room){client.matchId=room.id;room.setConnected(user.id,true);const assignment=room.player(user.id);sendClient(client,'match:resumed',{matchId:room.id,mode:room.mode,assignment,players:room.players});sendClient(client,'chat:history',{room:'match',roomId:room.id,messages:registry.chatHistory(room.id)});room.sync(user.id)}return}if(!client.id)throw new Error('Önce kullanıcı oturumu açılmalı.');handleAuthenticated(client,message)}catch(error){sendRaw(ws,'error',{message:error.message});if(error.message.includes('State güncel değil')){const room=client.id&&gameRooms.forUser(client.id);if(room)room.sync(client.id)}}});
  ws.on('close',()=>{connections.delete(client);if(client.id){matchmaker.leave(client.id);const room=gameRooms.forUser(client.id);if(room)room.setConnected(client.id,false);if(online.get(client.id)===client)online.delete(client.id);emitRelated(client.id)}broadcastStats()});
});
const heartbeat=setInterval(()=>{for(const client of connections){if(!client.alive){client.ws.terminate();continue}client.alive=false;client.ws.ping()}gameRooms.cleanup()},30000);heartbeat.unref();
function shutdown(){clearInterval(heartbeat);for(const client of connections)client.ws.close(1001,'Sunucu kapanıyor');wss.close();server.close();try{registry.close()}catch{}setTimeout(()=>process.exit(0),250)}
if(require.main===module){process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);server.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`KANTİN http://${process.env.HOST||'127.0.0.1'}:${port}`))}
module.exports={server,wss,websocketRequestAllowed};
